// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecepiCRUD.Entity;

#nullable disable

namespace RecepiCRUD.Entity.Migrations
{
    [DbContext(typeof(RecepiContext))]
    partial class RecepiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecepiCRUD.Entity.Recepi", b =>
                {
                    b.Property<int>("RecepiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecepiId"));

                    b.Property<string>("RecepiDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecepiImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecepiName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecepiId");

                    b.ToTable("Recepies");
                });
#pragma warning restore 612, 618
        }
    }
}
